"""Add is_banned field to User

Revision ID: 219603b76301
Revises: 
Create Date: 2025-06-27 01:06:31.426258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219603b76301'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
